const XS_BREAKPOINT = 0
const SM_BREAKPOINT = 600
const MD_BREAKPOINT = 900
const LG_BREAKPOINT = 1200
const XL_BREAKPOINT = 1500

export default {
    XS_BREAKPOINT,
    SM_BREAKPOINT,
    MD_BREAKPOINT,
    LG_BREAKPOINT,
    XL_BREAKPOINT,
}
