export const FETCH_PLANETS = 'FETCH_PLANETS'
export const FETCH_PLANETS_DONE = 'FETCH_PLANETS_DONE'
export const FETCH_PLANETS_ERROR = 'FETCH_PLANETS_ERROR'
export const RESET_PLANETS = 'RESET_PLANETS'
