export const FETCH_STARSHIPS = 'FETCH_STARSHIPS'
export const FETCH_STARSHIPS_DONE = 'FETCH_STARSHIPS_DONE'
export const FETCH_STARSHIPS_ERROR = 'FETCH_STARSHIPS_ERROR'
export const RESET_STARSHIPS = 'RESET_STARSHIPS'
