export const FETCH_VEHICLES = 'FETCH_VEHICLES'
export const FETCH_VEHICLES_DONE = 'FETCH_VEHICLES_DONE'
export const FETCH_VEHICLES_ERROR = 'FETCH_VEHICLES_ERROR'
export const RESET_VEHICLES = 'RESET_VEHICLES'
